// =============================================
// VARIANT SYSTEM — 10 Distinct Design Identities
// Each variant has a unique layout, spacing, typography,
// card style, hero layout, and animation profile.
// Variant is assigned deterministically from config hash.
// =============================================

const hashString = (str) => {
  let hash = 5381;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) + hash) + str.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash);
};

export const assignVariant = (config) => {
  const key = `${config.storeName}|${config.category}|${config.designStyle}|${config.brandTone}`;
  return hashString(key) % 10;
};

// --------------- 10 Variant Definitions ---------------

export const VARIANTS = [
  {
    id: 0,
    name: 'Classic Premium',
    // Hero
    heroLayout: 'centered',      // centered | split | fullscreen | magazine | diagonal | stacked
    heroMinHeight: '72vh',
    heroBgType: 'subtle',        // subtle | tinted | dark | gradient | none
    // Cards
    cardStyle: 'elevated',       // elevated | bordered | borderless | glass | offset | minimal | magazine
    cardRadius: '8px',
    cardImageRatio: '85%',
    showCardBorder: true,
    // Nav
    navStyle: 'solid',           // solid | glass | bordered | minimal | dark-solid
    navHeight: '60px',
    navPosition: 'top',
    // Typography
    heroTitleSize: 'clamp(2.4rem, 5vw, 4rem)',
    heroTitleWeight: '700',
    heroTitleTransform: 'none',
    heroTitleSpacing: '-0.03em',
    // Grid
    gridCols: 4,
    tabletCols: 2,
    mobileCols: 1,
    gridGap: '1.25rem',
    // Animations
    animStyle: 'fade',           // fade | slide | scale | reveal | bounce | none
    // Misc
    showFeaturedProduct: false,
    useSectionRule: true,
    categoryBadgeStyle: 'pill',  // pill | box | line | none
    heroTaglineCase: 'none',
    heroCtaStyle: 'filled',      // filled | outlined | dual | ghost
    sectionSpacing: '5rem',
  },
  {
    id: 1,
    name: 'Editorial Magazine',
    heroLayout: 'magazine',
    heroMinHeight: '85vh',
    heroBgType: 'none',
    cardStyle: 'magazine',
    cardRadius: '0px',
    cardImageRatio: '120%',
    showCardBorder: false,
    navStyle: 'bordered',
    navHeight: '56px',
    navPosition: 'side',
    heroTitleSize: 'clamp(3rem, 7vw, 6rem)',
    heroTitleWeight: '300',
    heroTitleTransform: 'none',
    heroTitleSpacing: '-0.04em',
    gridCols: 3,
    tabletCols: 2,
    mobileCols: 1,
    gridGap: '0px',
    animStyle: 'reveal',
    showFeaturedProduct: true,
    useSectionRule: true,
    categoryBadgeStyle: 'line',
    heroTaglineCase: 'none',
    heroCtaStyle: 'outlined',
    sectionSpacing: '7rem',
  },
  {
    id: 2,
    name: 'Tech Precision',
    heroLayout: 'split',
    heroMinHeight: '80vh',
    heroBgType: 'dark',
    cardStyle: 'bordered',
    cardRadius: '4px',
    cardImageRatio: '90%',
    showCardBorder: true,
    navStyle: 'dark-solid',
    navHeight: '58px',
    navPosition: 'top',
    heroTitleSize: 'clamp(2rem, 4.5vw, 3.5rem)',
    heroTitleWeight: '800',
    heroTitleTransform: 'none',
    heroTitleSpacing: '-0.02em',
    gridCols: 4,
    tabletCols: 2,
    mobileCols: 1,
    gridGap: '1px',
    animStyle: 'slide',
    showFeaturedProduct: false,
    useSectionRule: false,
    categoryBadgeStyle: 'box',
    heroTaglineCase: 'none',
    heroCtaStyle: 'filled',
    sectionSpacing: '4rem',
  },
  {
    id: 3,
    name: 'Bold Impact',
    heroLayout: 'fullscreen',
    heroMinHeight: '100vh',
    heroBgType: 'tinted',
    cardStyle: 'offset',
    cardRadius: '0px',
    cardImageRatio: '95%',
    showCardBorder: true,
    navStyle: 'glass',
    navHeight: '64px',
    navPosition: 'top',
    heroTitleSize: 'clamp(3.5rem, 9vw, 8rem)',
    heroTitleWeight: '900',
    heroTitleTransform: 'uppercase',
    heroTitleSpacing: '-0.04em',
    gridCols: 3,
    tabletCols: 2,
    mobileCols: 1,
    gridGap: '1.5rem',
    animStyle: 'scale',
    showFeaturedProduct: true,
    useSectionRule: false,
    categoryBadgeStyle: 'none',
    heroTaglineCase: 'uppercase',
    heroCtaStyle: 'dual',
    sectionSpacing: '5rem',
  },
  {
    id: 4,
    name: 'Soft Organic',
    heroLayout: 'stacked',
    heroMinHeight: '70vh',
    heroBgType: 'gradient',
    cardStyle: 'glass',
    cardRadius: '20px',
    cardImageRatio: '100%',
    showCardBorder: false,
    navStyle: 'glass',
    navHeight: '64px',
    navPosition: 'top',
    heroTitleSize: 'clamp(2.2rem, 5vw, 3.8rem)',
    heroTitleWeight: '600',
    heroTitleTransform: 'none',
    heroTitleSpacing: '0em',
    gridCols: 3,
    tabletCols: 2,
    mobileCols: 1,
    gridGap: '1.5rem',
    animStyle: 'bounce',
    showFeaturedProduct: false,
    useSectionRule: false,
    categoryBadgeStyle: 'pill',
    heroTaglineCase: 'none',
    heroCtaStyle: 'filled',
    sectionSpacing: '5rem',
  },
  {
    id: 5,
    name: 'Dark Neon',
    heroLayout: 'centered',
    heroMinHeight: '80vh',
    heroBgType: 'dark',
    cardStyle: 'borderless',
    cardRadius: '6px',
    cardImageRatio: '90%',
    showCardBorder: false,
    navStyle: 'dark-solid',
    navHeight: '60px',
    navPosition: 'top',
    heroTitleSize: 'clamp(2.5rem, 6vw, 5rem)',
    heroTitleWeight: '700',
    heroTitleTransform: 'none',
    heroTitleSpacing: '-0.03em',
    gridCols: 4,
    tabletCols: 2,
    mobileCols: 1,
    gridGap: '1rem',
    animStyle: 'reveal',
    showFeaturedProduct: false,
    useSectionRule: false,
    categoryBadgeStyle: 'box',
    heroTaglineCase: 'none',
    heroCtaStyle: 'ghost',
    sectionSpacing: '5rem',
  },
  {
    id: 6,
    name: 'Glass Morphism',
    heroLayout: 'diagonal',
    heroMinHeight: '85vh',
    heroBgType: 'gradient',
    cardStyle: 'glass',
    cardRadius: '16px',
    cardImageRatio: '95%',
    showCardBorder: false,
    navStyle: 'glass',
    navHeight: '64px',
    navPosition: 'top',
    heroTitleSize: 'clamp(2.5rem, 5.5vw, 4.5rem)',
    heroTitleWeight: '700',
    heroTitleTransform: 'none',
    heroTitleSpacing: '-0.02em',
    gridCols: 3,
    tabletCols: 2,
    mobileCols: 1,
    gridGap: '1.5rem',
    animStyle: 'fade',
    showFeaturedProduct: true,
    useSectionRule: false,
    categoryBadgeStyle: 'pill',
    heroTaglineCase: 'none',
    heroCtaStyle: 'filled',
    sectionSpacing: '6rem',
  },
  {
    id: 7,
    name: 'Neo Brutalist',
    heroLayout: 'stacked',
    heroMinHeight: '75vh',
    heroBgType: 'none',
    cardStyle: 'offset',
    cardRadius: '0px',
    cardImageRatio: '100%',
    showCardBorder: true,
    navStyle: 'bordered',
    navHeight: '56px',
    navPosition: 'side',
    heroTitleSize: 'clamp(3rem, 8vw, 7rem)',
    heroTitleWeight: '900',
    heroTitleTransform: 'uppercase',
    heroTitleSpacing: '0em',
    gridCols: 4,
    tabletCols: 2,
    mobileCols: 1,
    gridGap: '0px',
    animStyle: 'none',
    showFeaturedProduct: false,
    useSectionRule: true,
    categoryBadgeStyle: 'box',
    heroTaglineCase: 'uppercase',
    heroCtaStyle: 'filled',
    sectionSpacing: '4rem',
  },
  {
    id: 8,
    name: 'Warm Editorial',
    heroLayout: 'split',
    heroMinHeight: '78vh',
    heroBgType: 'subtle',
    cardStyle: 'minimal',
    cardRadius: '4px',
    cardImageRatio: '110%',
    showCardBorder: false,
    navStyle: 'minimal',
    navHeight: '58px',
    navPosition: 'top',
    heroTitleSize: 'clamp(2.4rem, 5.5vw, 4.5rem)',
    heroTitleWeight: '300',
    heroTitleTransform: 'none',
    heroTitleSpacing: '-0.02em',
    gridCols: 3,
    tabletCols: 2,
    mobileCols: 1,
    gridGap: '2rem',
    animStyle: 'reveal',
    showFeaturedProduct: true,
    useSectionRule: true,
    categoryBadgeStyle: 'line',
    heroTaglineCase: 'none',
    heroCtaStyle: 'outlined',
    sectionSpacing: '6rem',
  },
  {
    id: 9,
    name: 'Premium Noir',
    heroLayout: 'fullscreen',
    heroMinHeight: '90vh',
    heroBgType: 'dark',
    cardStyle: 'borderless',
    cardRadius: '2px',
    cardImageRatio: '100%',
    showCardBorder: false,
    navStyle: 'dark-solid',
    navHeight: '60px',
    navPosition: 'top',
    heroTitleSize: 'clamp(2.8rem, 6vw, 5.5rem)',
    heroTitleWeight: '300',
    heroTitleTransform: 'uppercase',
    heroTitleSpacing: '0.08em',
    gridCols: 4,
    tabletCols: 2,
    mobileCols: 1,
    gridGap: '1.5rem',
    animStyle: 'fade',
    showFeaturedProduct: false,
    useSectionRule: false,
    categoryBadgeStyle: 'none',
    heroTaglineCase: 'uppercase',
    heroCtaStyle: 'ghost',
    sectionSpacing: '6rem',
  },
];

export const getVariant = (variantId) => VARIANTS[variantId] || VARIANTS[0];
